// 이 파일은 tools/gen_levels.py 로 생성됩니다. 직접 수정하지 마세요.
// 레벨을 바꾸려면 tools/gen_levels.py 수정 후 `python3 tools/gen_levels.py` 실행.

export interface LevelDef {
  id: string;
  name: string;
  theme: string;
  time: number;
  rows: string[];
}

export const LEVELS: LevelDef[] = [
  {
    id: '1-1',
    name: '카운트 초원',
    theme: 'field',
    time: 300,
    rows: [
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '                                                                             b                                    b                                      b',
      '             !  ?  ?                    BB?BB                                         BB!BBB                                        ?B!B?',
      '                                                             o           oo                                               o                        ooo',
      '                           ooo     oo     o              oo ###   ooo   ====            o     ooo                         ##          H            ===          oo           oo  F',
      '       ooo       o                 ##                    ######   ===                         ===            oo         ####                                    ###         ############',
      '   P                   m         ####         m   m   #########                   C                  m   m   ####     ######               m   m             ######   m     ############',
      '###########################   ####################################   #########################   #############################   ##################   ########################################',
      '###########################   ####################################   #########################   #############################   ##################   ########################################',
      '###########################   ####################################   #########################   #############################   ##################   ########################################',
    ],
  },
  {
    id: '1-2',
    name: '벽돌 언덕',
    theme: 'hill',
    time: 320,
    rows: [
      '',
      '',
      '',
      '',
      '',
      '',
      '                                                      b                                       b                                                        b',
      '                               ooooo!                          #####                               b',
      '         !  !                  =====            BB!BB           BB                                      BBB!BBB?BBB                                              !                BB?BB',
      '                                                                BB                       o                                    o   o          ooo',
      '                      BB                          o             BB                   oo ###     ooo       o                  BB  BB  BB      ===                                              oo  F',
      '      oo              BBoo                                  oo  BB      oo           ######     ===                          BB  BB  BB                    ooo            ===                ###########',
      '   P           m  6   BB   m                 m            6     BB    m   m   C   #########                   m   z     6    BB  BB  BB  H         m       ####      z         m          ##############',
      '########################################   #####################################################   ##########################################   ##########################   ###########################',
      '########################################   #####################################################   ##########################################   ##########################   ###########################',
      '########################################   #####################################################   ##########################################   ##########################   ###########################',
    ],
  },
  {
    id: '1-3',
    name: '무지개 협곡',
    theme: 'canyon',
    time: 340,
    rows: [
      '',
      '',
      '',
      '',
      '',
      '',
      '                                                                                b',
      '                                             b                                                             b                     b',
      '          !  !                                                              oooo              !                                     BB?BB',
      '                                 ooo                                                                   oooo',
      '                            ooo  ===                                                                                         oo                  F',
      '      ooo            o      ===             H        D          oo    o                   ooo                         oo     ###              ########',
      '   P             m                       m                     C   7                    m        7                  m     ######          m   ########',
      '##########################            ##########            #############            ################            #####################################',
      '##########################            ##########            #############            ################            #####################################',
      '##########################            ##########            #############            ################            #####################################',
    ],
  },
  {
    id: '1-4',
    name: '제로 동굴',
    theme: 'cave',
    time: 360,
    rows: [
      'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
      'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
      '',
      '',
      '',
      '                                                               o                                                                                             o',
      '                                                          oo   SS                                                                                        o   SS',
      '                                                          SS                                                                                             SS',
      '         !  !                                                                                     BB!BB?BB',
      '                             ooo                                                                                                       SSSSSSSSS                                           o',
      '                    ooo     =====                                                                   o                                  SSSSSSSSS                                         =====       F',
      '      oo                              o                              oo                                         D          oo                                                                     ######',
      '   P            z    ^^   m  ^^^      SS     z   C   8     SS      m      9    BBBBBBBBB   z  ^^       m                 C    z    2    oooo o      8     SS      z   m   9    BBBBBBBB   ^^^  m  ######',
      '####################################LLLLLL###############LLLLLL################         ######################LLLLLLLL##################################LLLLLLL################        #################',
      '####################################LLLLLL###############LLLLLL################ ooo H o ######################LLLLLLLL##################################LLLLLLL################ oooo!  #################',
      '####################################LLLLLL###############LLLLLL###############################################LLLLLLLL##################################LLLLLLL#########################################',
    ],
  },
  {
    id: '1-5',
    name: '제로의 탑',
    theme: 'tower',
    time: 400,
    rows: [
      'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
      'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
      'SS                                                SS',
      'SS                                                SS',
      'SS                                                SS',
      'SS                                                SS',
      'SS                                                SS',
      'SS                      o  o                      SS',
      'SS                    ======                      SS',
      'SS                                                SS',
      'SS        ====                        ====        SS',
      'SS                       Z                        SS',
      'SS  P + H                                    +    SS',
      '####################################################',
      '####################################################',
      '####################################################',
    ],
  },
];
